### PR TITLE
Added for autopilot improvement

### PR DESCRIPTION
**Pull request by wizzlebippi**
Added to increase stabilizer effectiveness to improve autopilot pitch tracking

### CODE REVIEW

**Comment by dga711** [comment]
@wizzlebippi Thank you for your pr. Could you please highlight the changed values for me? Thanks a lot.

**Comment by wizzlebippi** [comment]
I changed elevator_trim_effectiveness from 1 to 3.

**Review by dga711 — APPROVED** [review]

**Comment by dga711** [comment]
@wizzlebippi Thank you for your contribution. While we still think it could be fine tuned, we really like the change.

**Comment by wizzlebippi** [comment]
Thanks.  After poking around in the systems.cfg files for a number of aircraft, it appears that Asobo did not bother to tune any aircraft's autopilot.

Unfortunately, there's a few things missing preventing real improvement.  Autotrim needs to be delayed, and autotrim rate needs to be much slower.  For FLC and autothrottle to really work, especially together, there needs to be an acceleration limit.  I've submitted a feature request to have these parameters added to every aircraft.

**Pull request merged**
