### PR TITLE
CJ v0.4.0

### PR DESCRIPTION
**Pull request by TioPernas**
cj 0.4.0

### CODE REVIEW

**Comment by mattnischan** [comment]
@TioPernas I don't see any changes here. Did you intend to put in a pull request?

**Comment by TioPernas** [comment]
i'm sorry my bad, i misclicked. i'm notifying my discord group of new update on CJ Mod you had trough my repository, since working title doesn't have a discord server.

**Comment by TioPernas** [comment]
guess i'll have to find another way to do it, or maybe you know how to do it without "disturbing" main branch

**Comment by mattnischan** [comment]
No worries! We actually did open a Discord for this release, which you can find at https://discord.gg/s9uEFP

Should I close this then?

**Comment by TioPernas** [comment]
oh nice, i'll go for the discord and link the announcements channel to mine. Thanks. Yes you can close this. Thank you

**Comment by mattnischan** [comment]
No problem, glad we could help.

**Pull request closed without merging**
