### PR TITLE
CJ4: Added Bearing Pointers

### PR DESCRIPTION
**Pull request by mattnischan**
Addresses #33

### CODE REVIEW

**Review by dga711 — APPROVED** [review]
super awesome feature. and code like a pro ;)

**Comment by Frolic31** [comment]
Hello, 

I'm sorry, i'm not sure that i understand, i'm such a noob in software things.
Does that mean that CJ4 0.6.0 is an update to come and that you've added the "missing bearing pointers" issue to that future release ?


In real life i'm a professional pilot in France. I've noted some troubles/errors with the CJ4. I'm not sure i can help noticing that all but if that could help me, let me know and i ill write everything down. 
As I said, i don't know anything at programming so I don't know what is possible or not, and I guess that all requires such a long work.

Thanks for all the job you do, it's just awesome.

**Comment by mattnischan** [comment]
@Frolic31 Yes, that is correct. Bearing pointers have been implemented in this pull request and will be coming in the next release, which is 0.6.0.

We would love the feedback! Feel free to report issues here on GitHub as you encounter them.

**Comment by Frolic31** [comment]
So great, thanks again ! I'm so looking forward to try it :) 

Ok perfect, i will do it when i have some free time.

**Pull request merged**
