### PR TITLE
Cj4 pfd/mfd brightness upgrade

### PR DESCRIPTION
**Pull request by charles-vomacka**
Currently, the sim will darken the panel, including the backlit displays, when the ambient lighting is bright. The sim seems to accomplish this by darkening the shades of all of the colors – measurements indicate that it makes them at least 20% darker than was specified in the creation of the display. This has the effect of making the displays hard to read because it reduces contrast. It also seems unrealistic; the displays are very brightly backlit - designed to be readable even in bright ambient lighting. My plan is to fix this by making some of the colors used in the PFD/MFD 10% to 23% lighter and decreasing the opacity of the shaded backgrounds. This has the effect of increasing the maximum brightness of these displays. The displays can still be darkened with the brightness controls. 

I do not have a definitive reference that I have used. I could not point to any of the references as the definitive reference because there are too many variables that would affect color – camera sensor, exposure, and post-processing.

I found a few different shades of magenta and cyan being used. I could not see a reason for it, and suspect it was due to different people using different shades. This upgrade would fix this and standardize the colors that I have changed.

I have been flying the CJ4 with these changes for a couple of weeks now and think that it is an improvement. For example, I never really paid attention to the VNAV information on the MFD, because I could not read it without zooming in. With these changes it is readable without zooming in. I have not provided a screenshot showing the changes because a screenshot does not show them well – the changes have to be seen in Sim.

So far I have altered the following colors:

Magenta:  lightened by 23% to #FF73FF. I lightened this color the most. Viewing reference videos, this color does not appear to be a true magenta in the real unit. I expect that it is a lighter shade of magenta for the same reason that I am changing the colors – to provide more contrast. The Flight Director V-bar appears, in the reference videos, to be an even lighter shade of magenta –almost pink. I did not implement this, but can, if desired.

Cyan: lightened by 10% to #33FFFF. Lightening it by more than 10% washed it out too much.

Green: lightened 20% from #11d011 to #5AF25A.

Red: lightened 10% to #FF3333.

Darkorange: lightened 10% to #FFA333.

Horizon Indicator Blue: lightened 20% to #1D72FC.

Horizon Indicator Brown:: lightened 20% to #B97D5F.

I did not change the colors used for terrain, weather, red warnings, charts or checklists.

Questions:
Does this seem as if it will be acceptable to the team?

I have changed the majority of the colors by implementing CSS variables. I am not sure if this is the best approach; is there a reason I should not do it this way?

Are the following files used by the other WT Nav systems; is it OK to change them?
SvgConstraintElement.js
SvgFlightPlanElement.js
SvgWaypointElement.js

### CODE REVIEW

**Comment by flymypi** [comment]
I've been bugging everybody about css variables, just not gotten around to implementing them yet.
I appreciate the effort!!

As to the color changes themselves: What you said makes sense, but I think it would be best for @K20017 to judge that with his real flying experience on that plane.

**Comment by charles-vomacka** [comment]
@flymypi Yes, I expect that this pull-request may be somewhat controversial. In my experience using it for the last couple of weeks, unless you compare the new to the old, side-by-side, you probably will not notice the difference - except for magenta.

**Comment by charles-vomacka** [comment]
These are the reference videos that I used to get a sense of the colors.

https://youtu.be/xw9wbFoQKUM?t=104
https://youtu.be/MI3XM9z6edU?t=117
https://youtu.be/e0vcLONYVAc?t=137
https://youtu.be/uHsbp7BH9eM?t=130
https://youtu.be/swLwahgaxoQ?t=85
https://youtu.be/HvhoQuo3EsE?t=89
https://youtu.be/E0KFo3rMd4c?t=110
https://www.youtube.com/watch?v=ooOsuft6Ne8
https://youtu.be/L0rssDlT-e8?t=105
https://youtu.be/Huj6qygqpig?t=143
https://www.youtube.com/watch?v=W33vSg6kmOM
https://youtu.be/DHU7PccILfY?t=82
https://youtu.be/GUOvPZX1Fx8?t=53
https://www.youtube.com/watch?v=V9JtVb6sJcs
https://youtu.be/V9JtVb6sJcs?t=113
https://youtu.be/V9JtVb6sJcs?t=127

**Comment by dga711** [comment]
Just one thing I remember, at the very beginning I've put css filters into the pfd/mfd CSS to give it more shine. Which might also have altered the colors.
Maybe see what happens when those are taken out.

**Comment by charles-vomacka** [comment]
@dga711 I do not know how to do that. Can you provide a hint?

**Comment by charles-vomacka** [comment]
@dga711 I take measurements at night - dark ambient lighting - and as I recall, the colors measured true. Magenta was true magenta, cyan true cyan... etc.

**Comment by charles-vomacka** [comment]
@dga711 I Googled CSS Filter. If I search the PFD.css and MFD.css for the word - filter - it is not found.

**Comment by dga711** [comment]
Hmm....let me check. Maybe I've taken them out some time ago 😬

**Comment by dga711** [comment]
@charles-vomacka Oh. It actually was in CJ4_FMC.css line 32 not PFD/MFD. Nvm then

**Comment by flymypi** [comment]
@charles-vomacka not sure about whites and blacks (watch out, there's a few), but yellow and red would certainly be sensible.
That being said, don't feel pressured to do that work, there's only a finite amount of CSS changes left to be done.

Choosing the values, we fill them with in the end is pretty much up to the teams general impression.

**Comment by charles-vomacka** [comment]
@flymypi 
I think I have finished. I converted dark-grey, yellow, red and orange to CSS variables without changing their color values. I also lighted light-grey by 3% - it is mainly used in the engine and systems instrument labels. I plan to leave the pull request as a draft while I do more testing and while awaiting K20017's review, unless you would like otherwise.

**Comment by flymypi** [comment]
@charles-vomacka That sounds good to me. Thanks for taking over this tedious work!

**Comment by charles-vomacka** [comment]
@flymypi
I also found  a couple of typos in the color specification for the flight director cross-pointers. (I likely introduced them during PFD Touchup). I corrected them in the latest commit.

**Comment by charles-vomacka** [comment]
@flymypi 
If you have more tedious work that is backlogged, let me know, and if it is not above my skill level, I would be happy to help out.

**Comment by charles-vomacka** [comment]
@flymypi 
Oh, I forgot to mention that I found a few colors that were only used a few times. I did not convert these. I added a comment next to most of them - one off color. This will allow you to search and view them if you like. I can remove the comments if you like.

**Comment by charles-vomacka** [comment]
I did more testing and have not found any issues - elements with no color because of a typo. 

Because of the hint @dga711 gave, I read up on CSS filters and learned that it may be possible to achieve the goal of this pull request with filters. I played with filters some, and could not get the display to look as bright as changing the colors makes it look, but someone more knowledgeable than I might make it look better. Thanks dga711, I learned something new.

@flymypi I am ready to change this to "Ready for review" unless you would like it to stay as draft.

**Comment by dga711** [comment]
Yeah. Don't use filters. I think its also bad for performance.
Just mentioned it because it could explain color differences between FMS and PFD/MFD

**Comment by charles-vomacka** [comment]
@flymypi @dga711 
Would you like me to implement CSS variables for the FMC and SAI without changing the color values?

**Comment by flymypi** [comment]
@charles-vomacka you can, but be aware that you might run into completely different colors there.

The FMC color edits preceed PFD/MFD while the SAI has only been edited recently by @slip664.

**Comment by charles-vomacka** [comment]
@flymypi  
OK, I will take a look at it and see what I find.

**Comment by flymypi** [comment]
@charles-vomacka actually, let me reverse on that a bit. I think it might be a better idea to wait until we merge @slip664s SAI changes before you touch that to avoid massive merge conflicts.

So only look at the FMC for now.

**Comment by charles-vomacka** [comment]
@flymypi OK.
That reminds me, my recent altimeter touchup split entries in the CSS for the airspeed and altimeter. I am not a git merge expert, but expect that the changes of this pull request will not be applied to those entries.

**Comment by charles-vomacka** [comment]
@flymypi The first thing I see is two CSS files for the FMC. I assume that I change both. I am guessing that CJ4_FMC.css applies to most of the files and WT_FMC.css  applies to WT_FMC_Renderer.js.

**Comment by charles-vomacka** [comment]
@flymypi I did quick research on multiple style sheets. I believe that I add the colors to CJ4_FMC.css and they are inherited by WT_FMC.css. Is this correct.

**Comment by charles-vomacka** [comment]
@flymypi I have looked at the FMC files and they use colors differently than I have seen. I don't feel comfortable making changes to them with my current knowledge level.

**Comment by flymypi** [comment]
@charles-vomacka I'm not familiar with the FMC myself, but no problem at all!

You've done a lot of good work already, thank you very much.

When we prep the next version I suggest we go through the merges together.

Do you have a Discord account? That would make make

**Comment by charles-vomacka** [comment]
Yes, I am PositiveZero on discord.

**Comment by dga711** [comment]
> @flymypi I did quick research on multiple style sheets. I believe that I add the colors to CJ4_FMC.css and they are inherited by WT_FMC.css. Is this correct.

@charles-vomacka Yeah, the wt_fmc.css is just an additional css with our changes. It was done like that in the very early days to not touch the stock files too much ^^

**Comment by charles-vomacka** [comment]
@dga711 Understand. Probably like I felt when I started making changes to your work without a half way decent understanding yet of how it all fit together - I hope this does not mess things up. :grimacing:

**Pull request merged**
