### PR TITLE
WIP: CJ4: Changed TOGA to command 7.5 degrees pitch up.

### PR DESCRIPTION
**Pull request by charles-vomacka**
This is based on K20017's Discord comment: https://discord.com/channels/750764704175226992/767761280366805022/915658443564650526

### CODE REVIEW

**Review by dga711 — APPROVED** [review]

**Comment by charles-vomacka** [comment]
@dga711 K20017 DM'ed me on discord and clarified > "Want to make a correction, when in TO mode, the pitch bar is commanded to 10 degrees but when in GA mode, it's set to 7.5". 
So it seems the change in this PR is not valid.

**Comment by charles-vomacka** [comment]
@dga711 
I think a have a fix that correctly commands 10 degrees for TO, and 7.5 degrees for GA. It involves setting simvars, so want to do a lot of testing before pushing.

**Comment by dga711** [comment]
> @dga711 I think a have a fix that correctly commands 10 degrees for TO, and 7.5 degrees for GA. It involves setting simvars, so want to do a lot of testing before pushing.

Cool. Sounds interesting 👍

**Comment by charles-vomacka** [comment]
@dga711 
Upon further testing, the fix I have does NOT work. I would disregard this PR. I will play around with it more and if I come up with something I will submit a new PR. I am not optimistic - I am not sure there is a way to command the autopilot to a specific pitch other than setting TOGA.

**Comment by charles-vomacka** [comment]
Is it OK if I close and delete this PR - this won't cause any problems?

**Comment by dga711** [comment]
> Is it OK if I close and delete this PR - this won't cause any problems?

Hey sure. Thanks for looking into it.

**Pull request closed without merging**
