### PR TITLE
CJ4: Add animated weather bug to compass

### PR DESCRIPTION
**Pull request by dga711**
- adds the animated radar bug to compass in pfd/mfd
- this pr pulls in NDCompass.js to our repo

image

VIDEO: https://streamable.com/nlri6c

### CODE REVIEW

**Comment by mattnischan** [comment]
When you're moving, I think the radar data updates in a sweep type fashion. I'm wondering if the bug plus the sweep will look off in some way.

**Comment by dga711** [comment]
> When you're moving, I think the radar data updates in a sweep type fashion. I'm wondering if the bug plus the sweep will look off in some way.

Dang. You are right. Will have to check for the logic there ^^

**Comment by dga711** [comment]
Since for now it seems impossible to sync with the radar cone of the game. This will be on hold. :(

**Comment by K20017** [comment]
But it looks cool and nobody is gonna care for now.  Merge merge merge!

**Review by mattnischan — APPROVED** [review]

**Pull request merged**
