### PR TITLE
Update CJ4_MFD.js Fix Elevator Trim Indicators

### PR DESCRIPTION
**Pull request by Danice737**
Fix Elevator Trim Indicators so they move the right direction along with a change to CJ4_SHARED.js

### CODE REVIEW

**Comment by J-Hoskin** [comment]
This is currently being worked on and should be fixed for upcoming release. Also a duplicate issue so I will close. Thanks for the suggestion.

**Comment by J-Hoskin** [comment]
Apologies ahah, I am in the train and thought this was a issue. I will review once I get home.

**Review by J-Hoskin — APPROVED** [review]
Nice job. In the future, since these fixes are so closely related, I would put them in one PR so its easier to work on and ensure both gauges are consistent.

**Comment by dga711** [comment]
Thank you for your contribution!

**Comment by J-Hoskin** [comment]
No worries :) I may have made a mistake then.

Also you can see in the picture below, the cursor is in the middle of the green. I can only assume that this is the natural position (no elevator). Which means the cursor needs to start in the middle of the green block? @K20017 can you confirm how this dam thing is meant to work?

image

**Comment by Danice737** [comment]
I had this question when trying to find how far to move the green box, I couldn't find a good pic of gauge I could confirm was just before takeoff for a starting cursor setting. So I only moved the green bar to match. and not the 0,0 position of cursor. It's not a hard change to move the cursor when we know the default neutral indication.

**Comment by K20017** [comment]
I assume the bottom of the green is 0 deflection on the elevator. The reason why the green box goes more into the nose down position is because you don't want the nose to pop up prematurely on takeoff.

**Comment by J-Hoskin** [comment]
@Danice737 after a very confusing conversation with the others I still have no idea what these trims are meant to be. Are you please able to revert my label changes and we'll stick with what you had for now until someone says otherwise?

**Comment by Danice737** [comment]
My change makes the cursors move and indicate in the right direction so when you add  pitch down the cursor moves to the top and when you add pitch up trim the cursors move to the bottom of the gauge. and fixed the green band on the ECIS,

**Comment by dga711** [comment]
We already have a brunch up to touch up some things. But it was not your changes that caused the confusion.
It is all fine for now.

**Pull request merged**
