### PR TITLE
CJ4: Persistent cabinlights setting

### LINKED ISSUE #389: Passengers Cabin lights always "on"
I noticed that from version 5.0 to version 6.0 it is no longer possible to manage the passenger cabin lights from the FMC, which always remain "on" each time the program is restarted. The problem seems to be an interference with the avionics switch  device. I changed the following lines   of the system.cfg,  by putting the parameter 10 instead 28, this seems to fix in part the issue:
 
 #cabin
lightdef.31 = Type: 13 # Index: 0 # LocalPosition: 6.5,0,3 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10
lightdef.32 = Type: 13 # Index: 0 # LocalPosition: 3.6,0,2.72 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10
lightdef.33 = Type: 13 # Index: 0 # LocalPosition: 0.5,0,3 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10
lightdef.34 = Type: 13 # Index: 0 # LocalPosition: -3,0,3 # LocalRotation: 0,0,0 # EffectFile: LIGHT_CJ4_CabinOmni # PotentiometerIndex: 10

However, this modification does not allow the management of the passenger cabin lights from the FMC in any case.
Any suggestions to fix it? Thx

### PR DESCRIPTION
**Pull request by dga711**
closes #389

### CODE REVIEW

**Review by cwburnett — APPROVED** [review]

**Comment by cwburnett** [comment]
@dga711 is it worth defaulting these always to off to eliminate the "flashlight bug"?
https://github.com/Working-Title-MSFS-Mods/fspackages/issues/309
I think if we default to off, then we'd close 309. Up to you though, we can also just document it.

**Comment by dga711** [comment]
Could be worth it, i don't really have a strong opinion here
Only downside could be that pilots newer realize there are any cabin lights :)

**Comment by J-Hoskin** [comment]
There is a hotkey for cabin lights i believe. Can u hook them up to that? Makes them a lil more discoverable

**Comment by K20017** [comment]
> There is a hotkey for cabin lights i believe. Can u hook them up to that? Makes them a lil more discoverable

Do you mean the small panel behind the copilot's head so they can turn on and off the cabin lights?  It's not even modeled remotely well enough :/

**Comment by J-Hoskin** [comment]
@K20017 No I mean there is a keyboard shortcut to turn on and off cabin lights. I guess most people don't know about it but it would be worth looking into hooking it up to our cabin lights

**Comment by dga711** [comment]
@J-Hoskin But isn't that meant for the cockpit cabin lights?

**Comment by cwburnett** [comment]
If we want to tie these up to a keyboard or set them to default to not break the flashlight, we can do that in a separate PR.

**Pull request merged**
