### PR TITLE
CJ4-FMS-dspl/tune

### PR DESCRIPTION
**Pull request by slip664**
- Fixed COM 1/2 Frequency parser #1087 
- clean up and correct DSPL MENU

### CODE REVIEW

**Comment by MartyAlcide** [comment]
stop

**Comment by MartyAlcide** [comment]
stop

**Comment by mattnischan** [comment]
@MartyAlcide Stop what? Is this in reference to this pill request in some way?

**Review by dga711 — CHANGES_REQUESTED** [review]
I think I see an merge issue here? CJ4_FMC_DsplMenuPage seems to revert some stuff we added

**Review by dga711 — APPROVED** [review]

**Pull request merged**
