### PR TITLE
Don't display wind data while on ground

### LINKED ISSUE #50: G1000: Hide wind display when aircraft on ground.
I believe there's a simvar for is flying. Need to add a condition of is flying for wind display.

### PR DESCRIPTION
**Pull request by tavip**
Fixes #50

### CODE REVIEW

**Comment by tavip** [comment]
I'll update the PR soon, there is an issue which keeps "NO WIND DATA" showing when the airplane is on the ground, even when wind data is off.

**Comment by mattnischan** [comment]
Hi @tavip, thanks for contributing!

Was the force-push you made the update you were referring to?

**Comment by tavip** [comment]
@mattnischan yep, it should be good for merge now

**Review by kaosfere — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
