### PR TITLE
CJ4: dep/arr page fixes

### PR DESCRIPTION
**Pull request by tscharlii**
Arrivals: Enable paging for transitions, e.g. EDDK: NVO transition is selectable now
Arrival/Approach Filter: trailing space in approach runway does not prevent match, e.g. EDDC
Minor improvements to arrivals and departure pages

### CODE REVIEW

**Review by knighty — COMMENTED** [review]
I don't do work on the CJ4 but tabs need changing to spaces throughout in several places

**Comment by dga711** [comment]
@tscharlii Thank you for your contribution. I will test it later today, as this one was on our todo list.

**Review by dga711 — CHANGES_REQUESTED** [review]
Did test it for a little bit. Here are my findings. Which must not be all caused of your changes I didn't really do back and forth testing. But it would be nice to have them fixed.

- https://streamable.com/p819tq It scrolls away the runways, which i think should stay in that case. But we would have to ask @K20017 what the correct behavior is
- same as above for approaches and trans when an approach is selected
- https://i.imgur.com/n0fwEim.png the stars and approaches should be small text. add [s-text]

For a better reference, here is part of a video @K20017 made using the rw FMS https://streamable.com/ms41n4

In general our display of the ARR page is not yet 100% true to real life. But as a first iteration I think it would be good enough with the points fixed.

**Comment by tscharlii** [comment]
Working on it. The first and second point require more complicated changes than the commits so far and I did not get it right on my first try. So I have some questions in return:

- Is there another way to test the logic than starting the game and hopping in a CJ4? The last picture on the announcement page https://forums.flightsimulator.com/t/cj4-community-mod-by-working-title-released/280375, which shows the about page, looks like some kind of simulator for the simulator (inception detected)
- How do I view the javascript console and see exceptions, console.log output, maybe syntax errors

**Comment by dga711** [comment]
> * Is there another way to test the logic than starting the game and hopping in a CJ4?
You already know about this ? https://github.com/dga711/msfs-webui-devkit

**Comment by tscharlii** [comment]
Didn't know it yet. That sounds about right.

**Review by dga711 — APPROVED** [review]
@tscharlii That was quick. I tested it and it was flawless. Really really good!

Again, thank you for your contribution. This helps a lot!

**Comment by tscharlii** [comment]
You are welcome. I enjoy flying with this mod very much! Glad to help improving it.

**Pull request merged**
