### PR TITLE
CJ4: Revamped (a little) error messages in the FMC

### PR DESCRIPTION
**Pull request by panourgue**
**updated** (see conversation below) 

~~[example of the problem](https://streamable.com/u0pn96), at least I think it's a problem :)))~~

~~Tested on several pages, didn't see any adverse behaviour, but you use this function in many places, so idk.~~

### CODE REVIEW

**Comment by panourgue** [comment]
meh

**Comment by panourgue** [comment]
thought I saw a problem, but no

**Comment by dga711** [comment]
I think I remember (from @K20017 s video where he shows input checks) that your input will remain on error.

If that is true, then the problem is more with weird things going on with it in general on error and clr/del etc. which must be streamlined. Because yeah, it is annoying.

**Comment by panourgue** [comment]
@dga711  I'm pretty sure that there are two types of error/message notifications in proline:
- related to user input (like "invalid entry") shown actually inside the scratchpad
- line underneath the scratpad is for messages/warnings that are more to do with general state from the fms

> weird things going on with it in general on error and clr/del etc. which must be streamlined

I made some changes already.  👀 [check this out](https://streamable.com/zxu8by) 👀 
But I a bit reluctant to PR this because it replaces several base methods from "fmc" object in runtime and some of your code.

**Comment by dga711** [comment]
that looks pretty cool.

i knew that behavior, but imo i like the errors beneath better. but ofc it is no "study level" :-D

good work. i think we should let @K20017 give his opinion on all this and then continue

**Comment by cwburnett** [comment]
Yes, will leave this one for @K20017 to approve or ask for a change....

**Comment by panourgue** [comment]
For clarification: this pr just straight up removes last user input when "invalid entry" occurs. Video link in [my comment](https://github.com/Working-Title-MSFS-Mods/fspackages/pull/406#issuecomment-716623472) does not represet it.

**Comment by dga711** [comment]
image

But as I already said, besides that, there is something funky going on when you start typing again and maybe we can fix that. I just can't really describe it. @panourgue

**Comment by dga711** [comment]
As you can see in this video from @K20017 he presses CLR and it wouldn't go to show CLR/DELETE, but instead showing last input and start removing letters from that.
https://streamable.com/d2elfu

**Review by dga711 — CHANGES_REQUESTED** [review]
see above

**Comment by panourgue** [comment]
@dga711 Looks similar to [what I what I tried at home](https://streamable.com/zxu8by). Maybe I update this pr so you could at least look at my idea?

**Comment by dga711** [comment]
yeah, i mean if you can get it to work it would certainly give us "study level" points :D

**Comment by panourgue** [comment]
@dga711 Tried to make it as intuitive as possible and similar to @K20017's video.

**Comment by dga711** [comment]
Thank you very much. Will test.

**Review by dga711 — APPROVED** [review]
Very nice!

**Comment by cwburnett** [comment]
Looks great, merging, thanks!

**Pull request merged**
