### PR TITLE
CJ4 Scratchpad & Random fixes

### PR DESCRIPTION
**Pull request by dga711**
Makes the errors in scratchpad render independent of inOut. So we don't have to block LSK on error, which introduced other problems.
Some minor other fixes which i met on the way.

- [x] scratchpad error independent of inout
- [x] simbrief import "errors" are now msg
- [x] no lsk event on rwy on route page
- [x] fix decel error when no runway

### CODE REVIEW

**Comment by dga711** [comment]
@panourgue review pls

**Comment by panourgue** [comment]
@dga711 What's an LSK? Is it L0..L6 and R0..R6 button?

**Comment by K20017** [comment]
> @dga711 What's an LSK? Is it L0..L6 and R0..R6 button?

LSK is Line select key. The 6 buttons on the left and right of the FMC display. So you can identify them like LSK 1R or LSK 6L

**Review by panourgue — CHANGES_REQUESTED** [review]
Suggestion: instead of plugging previous scratchpad's value into lsk, just close error message and put that value back? User would have to click lsk two times, but imo it's more intuitive

**Review by J-Hoskin — APPROVED** [review]

**Pull request merged**
