### PR TITLE
CJ4: Accept QNH in HPA in "takeoff" and "approach" pages

### PR DESCRIPTION
**Pull request by panourgue**
[Check this video](https://streamable.com/btdr39)

I have now idea how (or even if) this stuff is done IRL.
But please please please at least consider this change 🥺🙏🙏🙏

Hectopascals are used in places like Europe, Asia, Africa, Australia and South America…

(unrelated to #397)

### CODE REVIEW

**Comment by cwburnett** [comment]
@panourgue thanks for the PR, believe it or not, I have a draft PR in review right now for a mod setting switch to convert the entire FMS between metric and imperial units, and when doing this I also added in hPa. I'm going to leave this open because you did a few things a little differently that I may want to incorporate. Thanks again!

**Comment by panourgue** [comment]
Yeah, I saw your pr, but only after I pr'ed this one 🤦
Wanted to try it, but it just crashed the fms.

@cwburnett Hopefully you'll keep metric units and hpa separate (since they do not correspond one to one) ?

**Comment by cwburnett** [comment]
@panourgue yes you will be able to enter hPA even without being in metric units for weight. But leave this PR open please for now, thanks.

**Comment by panourgue** [comment]
aye aye :)

**Comment by cwburnett** [comment]
@panourgue thanks for this one also, I did merge this into mine mostly, but left out part of it to reflect how the real jet operates. Thanks!

**Pull request closed without merging**
