### PR TITLE
Cj4/cosmetics v5

### PR DESCRIPTION
**Pull request by flymypi**
Mainly focused on Altimeter and PFD Menu, resulting in the following fixes/additions:

**ALTIMETER**
- [x] Added correct Target Altitude initialization behaviour
- [x] Added Target and Current Altitude display in meters

**MINIMUMS**
- [x] Made minimums toggle-able (OFF/BARO/RA)
- [x] Fixed display of BARO mins pointer & text
- [x] Added RA mins pointer & text
- [x] Improved trigger logic for both aural warnings (thx @dga711)
- [x] Made both minimum values persistent (but mode defaulting to off)

**V-SPEEDS**
- [x] Fixed V-Speed selection ranges
- [x] Added checkboxes to V-Speeds to make them toggle-able
- [x] Made all selected V-Speed values persistent (but mode defaulting to off)
- [x] Added correct deactivation logic on change
- [x] Added correct deactivation logic in both relevant speedtape conditions

**MENUS**
- [x] Improved general look of menus
- [x] Added two new types of item (RadioRange, CheckboxRange)
- [x] Added working OVERLAYS pages for PFD and MFD menus
- [x] Added partially working MAP SYMBOLS page in LWR MENU
- [x] Added BARO SET page with working Baro preselect and STD-mode toggle
- [x] Fixed FD mode not switching with FD off
- [x] Prepared TAWS page
- [x] Prepared RADAR page with submenu

**TODO**
- [x] Some more menu visuals
- [ ] V-Speed bumping

### CODE REVIEW

**Comment by Hesynergy** [comment]
Lovely! Such a sweetie of a bird! Are the fixes available an update?

Thanks,
Chas

**Review by flymypi — COMMENTED** [review]
> Lovely! Such a sweetie of a bird! Are the fixes available an update?
> 
> Thanks,
> Chas


Thank you very much, on behalf of the entire team.

There's a couple of issues I still have with this PR, so we'll have to wait and see whether it makes it into the next release.
This project being open source, you can of course still test this PR beforehand.

**Comment by Hesynergy** [comment]
￼￼How often are "commits" published￼?

Thanks for your work!

Chas￼

**Comment by dga711** [comment]
What is left to do or not working? @flymypi

**Comment by flymypi** [comment]
@Hesynergy when they meet all requirements, they do.

@dga711 It's working fine within technical limitations.
In other words, when you open the menus, change what you want to change and return, everything is fine.
When something changes (because the menu dict was filled when opening), the state of opening plus made changes are enforced. This negative impact could be minified if the `fillDictionary` method was called on opening submenus as well.

Feature-wise, I wanted to also implement V-Speed bumping but I don't currently have the time for that.

**Pull request merged**
